[workspace]
resolver = "2"
members = [
    "crates/crucible-sim",
    "crates/crucible-ai",
    "crates/crucible-evo",
    "crates/crucible-server",
    "crates/crucible-client-wasm",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"

crucible-sim = { path = "crates/crucible-sim" }
crucible-ai = { path = "crates/crucible-ai" }
crucible-evo = { path = "crates/crucible-evo" }

[profile.release]
opt-level = 3
lto = "thin"

[profile.dev]
opt-level = 1
