//! Match orchestration: state container, the turn lifecycle, command
//! application, action budget, win check, and helpers shared by the other
//! modules.
//!
//! The game is strictly alternating-activation: only `self.active` may issue
//! commands; they execute immediately. [`Command::EndTurn`] runs the
//! end-of-activation resolution (turret fire → sweep → fog → win check) and
//! then the opponent's start-of-activation (income → production → unit resets
//! → fog). A player-facing round is the P0/P1 activation pair; the public
//! `turn` counter remains the activation/replay compatibility counter.

use serde::{Deserialize, Serialize};

use crate::entity::{
    building_stats, unit_stats, Building, BuildingType, EntityId, Player, ResourceBundle,
    ResourceType, Unit, UnitType, CRYSTAL_REFINERY_BASE_YIELD_PER_TURN, HQ_INCOME_PER_TURN,
    REFINERY_BASE_YIELD_PER_TURN, REPAIR_COST_DEN, REPAIR_COST_NUM, REPAIR_HP_DEN, REPAIR_HP_NUM,
    REPAIR_MIN_COST, RESEARCH_PER_LAB_PER_TURN,
};
use crate::map::{Map, MAP_SIZE, MAP_TILES};
use crate::orders::{Command, CommandError, NEIGHBOR_OFFSETS};
use crate::tech::{tech_info, TechId};
use crate::tiles::within_range;

/// Runtime-tunable match settings. Tests override via a builder.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct GameConfig {
    pub max_queue: usize,
    /// Actions each player may issue per own turn (`EndTurn` is free).
    pub actions_per_turn: i32,
    pub starting_ore: i32,
    /// Small opening material reserves keep the first industrial choices
    /// playable before a remote Steel/Coal refinery is established.
    #[serde(default)]
    pub starting_steel: i32,
    #[serde(default)]
    pub starting_coal: i32,
    #[serde(default)]
    pub starting_crystal: i32,
    /// Fraction of a building's cost refunded on sell (50/100 = 50%).
    pub sell_refund_num: i32,
    pub sell_refund_den: i32,
    /// Match length cap in turns. `<= 0` disables the timeout entirely (live
    /// matches are unlimited; training matches set an explicit cap so
    /// degenerate self-play games cannot run forever).
    pub timeout_turns: i32,
}

impl Default for GameConfig {
    fn default() -> Self {
        GameConfig {
            max_queue: 5,
            actions_per_turn: 16,
            starting_ore: 450,
            // The opening reserve covers one refinery plus the first core
            // production structure; later steel/coal comes from remote
            // deposits rather than silently making the factory unbuildable.
            starting_steel: 300,
            starting_coal: 100,
            starting_crystal: 0,
            sell_refund_num: 1,
            sell_refund_den: 2,
            timeout_turns: crate::MATCH_TIMEOUT_TURNS,
        }
    }
}

/// A player's research progress: an accruing pool of points (generated by
/// Tech Labs), the set of completed techs, and the tech currently being
/// researched (at most one at a time).
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct PlayerResearch {
    pub points: i32,
    pub researched: Vec<TechId>,
    pub researching: Option<TechId>,
}

impl PlayerResearch {
    pub fn has(&self, tech: TechId) -> bool {
        self.researched.contains(&tech)
    }
}

/// Aggregate research modifiers as integer percentage numerators (den = 100).
/// `range_add`/`air_range_add` are additive tiles.
#[derive(Clone, Copy, Debug)]
pub struct TechEffects {
    pub dmg_num: i32,
    pub air_dmg_num: i32,
    pub hp_num: i32,
    pub range_add: i32,
    pub air_range_add: i32,
    pub yield_num: i32,
    pub power_num: i32,
}

impl TechEffects {
    fn base() -> Self {
        TechEffects {
            dmg_num: 100,
            air_dmg_num: 100,
            hp_num: 100,
            range_add: 0,
            air_range_add: 0,
            yield_num: 100,
            power_num: 100,
        }
    }
}

/// Per-turn action budget (replaces the old realtime APM token bucket).
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ActionBudget {
    spent: i32,
    cap: i32,
}

impl ActionBudget {
    fn new(cap: i32) -> Self {
        ActionBudget { spent: 0, cap }
    }

    pub(crate) fn reset(&mut self) {
        self.spent = 0;
    }

    pub(crate) fn try_spend(&mut self) -> bool {
        if self.spent < self.cap {
            self.spent += 1;
            true
        } else {
            false
        }
    }

    pub fn spent(&self) -> i32 {
        self.spent
    }

    pub fn cap(&self) -> i32 {
        self.cap
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Debug)]
pub enum WinReason {
    HqDestroyed,
    Timeout,
    /// All 10 technologies researched (science victory).
    ScienceVictory,
    /// Controls ≥ 60% of passable, explored tiles (domination).
    MapControl,
}

#[derive(Clone, Serialize, Deserialize, Debug)]
pub enum EventKind {
    BuildingPlaced {
        player: Player,
        btype: BuildingType,
        tile: (u8, u8),
    },
    UnitTrained {
        player: Player,
        utype: UnitType,
        tile: (u8, u8),
    },
    UnitDied {
        id: EntityId,
        owner: Player,
    },
    BuildingDestroyed {
        id: EntityId,
        owner: Player,
    },
    /// Generic extraction event for the four deposit types.
    ResourceMined {
        player: Player,
        resource: ResourceType,
        amount: i32,
    },
    /// Legacy event shapes retained for old consumers; new games emit
    /// `ResourceMined` instead.
    OreMined {
        player: Player,
        amount: i32,
    },
    CrystalMined {
        player: Player,
        amount: i32,
    },
    ResearchStarted {
        player: Player,
        tech: TechId,
    },
    ResearchComplete {
        player: Player,
        tech: TechId,
    },
    Attacked {
        attacker: EntityId,
        target: EntityId,
        damage: i32,
        /// Whether the defender's counterattack also resolved.
        countered: bool,
    },
    Sold {
        player: Player,
        btype: BuildingType,
        refund: ResourceBundle,
    },
}

#[derive(Clone, Serialize, Deserialize, Debug)]
pub struct GameEvent {
    pub turn: i32,
    pub kind: EventKind,
}

fn initial_round() -> i32 {
    1
}

/// The complete match state. The only mutable root of the simulation.
#[derive(Clone, Serialize, Deserialize, Debug)]
pub struct Game {
    pub config: GameConfig,
    pub map: Map,
    pub buildings: Vec<Building>,
    pub units: Vec<Unit>,
    pub ore: [i32; 2],
    /// Banked Steel extracted from Steel deposits.
    #[serde(default)]
    pub steel: [i32; 2],
    /// Banked Coal extracted from Coal deposits.
    #[serde(default)]
    pub coal: [i32; 2],
    /// Strategic crystal stockpile (spent on top-tier research).
    pub crystal: [i32; 2],
    /// Per-player research state.
    pub research: [PlayerResearch; 2],
    /// Monotonic activation number, starting at 1. This remains the replay
    /// and timeout compatibility counter; use `round` for the player-facing
    /// human+AI cycle.
    pub turn: i32,
    /// Player-facing round number, starting at 1. P0 and P1 activations share
    /// a round; it advances when P1 hands control back to P0.
    #[serde(default = "initial_round")]
    pub round: i32,
    /// Whose activation it is.
    pub active: Player,
    pub winner: Option<Player>,
    pub win_reason: Option<WinReason>,
    /// Whether the match has reached a terminal result. Kept separate from
    /// `winner` so a legitimate draw can end the match without naming a side.
    #[serde(default)]
    pub over: bool,
    pub budgets: [ActionBudget; 2],
    pub next_id: EntityId,
    /// All entity ids in allocation order, including entities removed after
    /// death or sale. This is runtime-only bookkeeping used by replay/ghost
    /// consumers to preserve creation-rank references across casualties.
    #[serde(skip)]
    pub entity_history: Vec<(EntityId, Player)>,
    pub events: Vec<GameEvent>,
    /// Number of commands dropped by the action budget, per player.
    pub dropped_commands: [u32; 2],
    /// Per-player fog-of-war memory.
    pub fog: [crate::fog::FogMemory; 2],
}

impl Game {
    pub fn new(map: Map, config: GameConfig) -> Self {
        let mut next_id = 1u32;
        let mut buildings = Vec::new();
        for (p, tile) in Player::ALL.iter().zip(map.hq_tiles.iter()) {
            let stats = building_stats(BuildingType::Hq);
            buildings.push(Building {
                id: next_id,
                owner: *p,
                btype: BuildingType::Hq,
                tile: *tile,
                hp: stats.hp,
                max_hp: stats.hp,
                queue: Vec::new(),
                progress: 0,
                construction_progress: 0,
                cooldown: 0,
                repaired_this_turn: false,
                rally: None,
            });
            next_id += 1;
        }
        let mut game = Game {
            config: config.clone(),
            map,
            buildings,
            units: Vec::new(),
            ore: [config.starting_ore; 2],
            steel: [config.starting_steel; 2],
            coal: [config.starting_coal; 2],
            crystal: [config.starting_crystal; 2],
            research: [
                PlayerResearch {
                    points: 0,
                    researched: Vec::new(),
                    researching: None,
                },
                PlayerResearch {
                    points: 0,
                    researched: Vec::new(),
                    researching: None,
                },
            ],
            turn: 1,
            round: 1,
            active: Player::P0,
            winner: None,
            win_reason: None,
            over: false,
            budgets: [
                ActionBudget::new(config.actions_per_turn),
                ActionBudget::new(config.actions_per_turn),
            ],
            next_id,
            entity_history: vec![(1, Player::P0), (2, Player::P1)],
            events: Vec::new(),
            dropped_commands: [0, 0],
            fog: [
                crate::fog::FogMemory::default(),
                crate::fog::FogMemory::default(),
            ],
        };
        // A new match starts with the HQs' immediate vision recorded. This
        // makes the first state diff and first tile inspection useful without
        // requiring a no-op command to prime fog memory.
        game.fog_phase();
        game
    }

    // -- lookups -------------------------------------------------------------

    pub fn alloc_id(&mut self) -> EntityId {
        let id = self.next_id;
        self.next_id += 1;
        id
    }

    pub(crate) fn record_entity_creation(&mut self, id: EntityId, owner: Player) {
        self.entity_history.push((id, owner));
    }

    /// Entity ids in allocator order, including dead and sold entities. The
    /// fallback keeps hand-built legacy fixtures useful when they do not
    /// populate runtime history.
    pub fn entity_ids_in_creation_order(&self, owner: Player) -> Vec<EntityId> {
        let mut ids: Vec<EntityId> = self
            .entity_history
            .iter()
            .filter(|(_, p)| *p == owner)
            .map(|(id, _)| *id)
            .collect();
        // Hand-built fixtures and old deserialized snapshots may have a
        // partially populated history. Preserve the recorded prefix, then
        // append any currently-live ids in allocator order. Normal games
        // never take this branch because every constructor records its id;
        // the fallback keeps ghost/replay consumers correct for legacy state
        // instead of silently dropping manually inserted entities.
        let mut missing: Vec<EntityId> = self
            .units
            .iter()
            .filter(|u| u.owner == owner)
            .map(|u| u.id)
            .chain(
                self.buildings
                    .iter()
                    .filter(|b| b.owner == owner)
                    .map(|b| b.id),
            )
            .filter(|id| !ids.contains(id))
            .collect();
        missing.sort_unstable();
        ids.extend(missing);
        ids
    }

    pub fn unit(&self, player: Player, id: EntityId) -> Option<&Unit> {
        self.units.iter().find(|u| u.id == id && u.owner == player)
    }

    pub fn unit_mut(&mut self, player: Player, id: EntityId) -> Option<&mut Unit> {
        self.units
            .iter_mut()
            .find(|u| u.id == id && u.owner == player)
    }

    pub fn building(&self, player: Player, id: EntityId) -> Option<&Building> {
        self.buildings
            .iter()
            .find(|b| b.id == id && b.owner == player)
    }

    pub fn building_mut(&mut self, player: Player, id: EntityId) -> Option<&mut Building> {
        self.buildings
            .iter_mut()
            .find(|b| b.id == id && b.owner == player)
    }

    /// Find any building (any owner) by id.
    pub fn any_building(&self, id: EntityId) -> Option<&Building> {
        self.buildings.iter().find(|b| b.id == id)
    }

    /// Find any unit (any owner) by id.
    pub fn any_unit(&self, id: EntityId) -> Option<&Unit> {
        self.units.iter().find(|u| u.id == id)
    }

    pub fn building_at(&self, tile: (u8, u8)) -> Option<EntityId> {
        self.buildings.iter().find(|b| b.tile == tile).map(|b| b.id)
    }

    /// The living unit occupying a tile, if any.
    pub fn unit_at(&self, tile: (u8, u8)) -> Option<EntityId> {
        self.units
            .iter()
            .find(|u| u.is_alive() && u.tile == tile)
            .map(|u| u.id)
    }

    /// The HQ building of a player, if alive.
    pub fn hq(&self, player: Player) -> Option<&Building> {
        self.buildings
            .iter()
            .find(|b| b.owner == player && b.btype == BuildingType::Hq)
    }

    pub fn push_event(&mut self, kind: EventKind) {
        self.events.push(GameEvent {
            turn: self.turn,
            kind,
        });
    }

    /// The four-resource stockpile for `player`.
    pub fn resources(&self, player: Player) -> ResourceBundle {
        let i = player.index();
        ResourceBundle::new(self.ore[i], self.steel[i], self.coal[i], self.crystal[i])
    }

    pub fn can_afford(&self, player: Player, price: ResourceBundle) -> bool {
        self.resources(player).can_afford(price)
    }

    pub fn spend_resources(&mut self, player: Player, price: ResourceBundle) -> bool {
        let Some(remaining) = self.resources(player).checked_sub(price) else {
            return false;
        };
        let i = player.index();
        self.ore[i] = remaining.ore;
        self.steel[i] = remaining.steel;
        self.coal[i] = remaining.coal;
        self.crystal[i] = remaining.crystal;
        true
    }

    pub fn add_resources(&mut self, player: Player, amount: ResourceBundle) {
        let i = player.index();
        let updated = self.resources(player).saturating_add(amount);
        self.ore[i] = updated.ore;
        self.steel[i] = updated.steel;
        self.coal[i] = updated.coal;
        self.crystal[i] = updated.crystal;
    }

    /// Per-turn income estimate from the current HQ/refinery state. Deposits
    /// are inexhaustible: only the static richness tier affects the yield.
    /// This is used by the client HUD and does not mutate the game.
    pub fn resource_income(&self, player: Player) -> ResourceBundle {
        let mut income = ResourceBundle::new(HQ_INCOME_PER_TURN, 0, 0, 0);
        let yield_num = self.tech_effects(player).yield_num;
        for b in self
            .buildings
            .iter()
            .filter(|b| b.owner == player && b.is_operational() && b.btype.is_refinery())
        {
            if let Some(resource) = self.map.resource_at(b.tile.0, b.tile.1) {
                if !self.map.has_resource_at(b.tile.0, b.tile.1) {
                    continue;
                }
                let amount = self
                    .refinery_yield(resource, self.map.resource_richness_at(b.tile.0, b.tile.1))
                    * yield_num
                    / 100;
                match resource {
                    ResourceType::Ore => income.ore += amount,
                    ResourceType::Steel => income.steel += amount,
                    ResourceType::Coal => income.coal += amount,
                    ResourceType::Crystal => income.crystal += amount,
                }
            }
        }
        income
    }

    /// The base extraction rate for a resource at a richness tier.
    pub fn refinery_yield(&self, resource: ResourceType, richness: u8) -> i32 {
        if richness == 0 {
            return 0;
        }
        let base = if resource == ResourceType::Crystal {
            CRYSTAL_REFINERY_BASE_YIELD_PER_TURN
        } else {
            REFINERY_BASE_YIELD_PER_TURN
        };
        base * i32::from(richness.clamp(1, 3))
    }

    /// Per-tile blocked overlay: tiles occupied by a building (terrain
    /// passability is separate, in [`Map::passable`]).
    pub fn blocked_grid(&self) -> Vec<bool> {
        let mut b = vec![false; crate::map::MAP_TILES];
        for x in &self.buildings {
            b[crate::map::tile_index(x.tile.0, x.tile.1)] = true;
        }
        b
    }

    // -- power ---------------------------------------------------------------

    /// Return (power_produced, power_consumed) for a given player.
    pub fn power(&self, player: Player) -> (i32, i32) {
        let mut produced = 0;
        let mut consumed = 0;
        let e = self.tech_effects(player);
        for b in &self.buildings {
            if b.owner == player && b.is_operational() {
                let stats = building_stats(b.btype);
                if stats.power > 0 {
                    // Superconductors boosts power-plant output.
                    let p = if b.btype == BuildingType::PowerPlant {
                        stats.power * e.power_num / 100
                    } else {
                        stats.power
                    };
                    produced += p;
                } else if stats.power < 0 {
                    consumed += -stats.power;
                }
            }
        }
        (produced, consumed)
    }

    /// True if a player's power consumption exceeds their power production.
    pub fn has_low_power(&self, player: Player) -> bool {
        let (prod, cons) = self.power(player);
        cons > prod
    }

    // -- command application ---------------------------------------------------

    /// Validate and apply a batch of commands for one player. Returns a
    /// per-command result so the server can report exactly which were dropped
    /// and why. Commands are applied in the order given; the action budget is
    /// shared across the batch.
    pub fn apply_commands(
        &mut self,
        player: Player,
        cmds: &[Command],
    ) -> Vec<Result<(), CommandError>> {
        cmds.iter().map(|cmd| self.apply_one(player, cmd)).collect()
    }

    fn apply_one(&mut self, player: Player, cmd: &Command) -> Result<(), CommandError> {
        self.validate_command(cmd)?;
        if cmd.costs_action() && !self.budgets[player.index()].try_spend() {
            self.dropped_commands[player.index()] += 1;
            return Err(CommandError::RateLimited);
        }
        self.execute(player, cmd.clone());
        Ok(())
    }

    fn execute(&mut self, player: Player, cmd: Command) {
        match cmd {
            Command::PlaceBuilding { btype, tile, .. } => {
                let stats = building_stats(btype);
                let _ = self.spend_resources(player, stats.resource_cost);
                let id = self.alloc_id();
                self.record_entity_creation(id, player);
                self.buildings.push(Building {
                    id,
                    owner: player,
                    btype,
                    tile,
                    hp: stats.hp,
                    max_hp: stats.hp,
                    queue: Vec::new(),
                    progress: 0,
                    construction_progress: 0,
                    cooldown: 0,
                    repaired_this_turn: false,
                    rally: None,
                });
                self.push_event(EventKind::BuildingPlaced {
                    player,
                    btype,
                    tile,
                });
                self.fog_phase();
            }
            Command::TrainUnit {
                building, utype, ..
            } => {
                let stats = unit_stats(utype);
                let _ = self.spend_resources(player, stats.resource_cost);
                if let Some(b) = self.building_mut(player, building) {
                    b.queue.push(utype);
                }
            }
            Command::SetRally {
                building, waypoint, ..
            } => {
                // Setting the rally to the building's own tile clears it
                // (right-click the producer to unset the point).
                if let Some(b) = self.building_mut(player, building) {
                    b.rally = if waypoint == b.tile {
                        None
                    } else {
                        Some(waypoint)
                    };
                }
            }
            Command::MoveGroup {
                units, waypoint, ..
            } => {
                self.execute_move_group(player, &units, waypoint);
                self.fog_phase();
            }
            Command::ClearMove { units, .. } => {
                self.execute_clear_move(player, &units);
                self.fog_phase();
            }
            Command::Attack { units, target, .. } => {
                self.execute_attack(player, &units, target);
                self.sweep_dead();
                self.check_win();
                self.fog_phase();
            }
            Command::StartResearch { tech, .. } => {
                self.research[player.index()].researching = Some(tech);
                self.push_event(EventKind::ResearchStarted { player, tech });
            }
            Command::Sell { building, .. } => {
                let btype = self.building(player, building).map(|b| b.btype);
                if let Some(bt) = btype {
                    let stats = building_stats(bt);
                    let refund = stats
                        .resource_cost
                        .scaled_floor(self.config.sell_refund_num, self.config.sell_refund_den);
                    self.add_resources(player, refund);
                    self.push_event(EventKind::Sold {
                        player,
                        btype: bt,
                        refund,
                    });
                    let id = building;
                    self.buildings.retain(|b| b.id != id);
                    self.fog_phase();
                }
            }
            Command::Repair { building, .. } => {
                let cost = self.repair_cost(building).unwrap_or(ResourceBundle::new(
                    REPAIR_MIN_COST,
                    0,
                    0,
                    0,
                ));
                if self.can_afford(player, cost) {
                    let index = self
                        .buildings
                        .iter()
                        .position(|b| b.id == building && b.owner == player && b.is_alive());
                    if let Some(index) = index {
                        if !self.buildings[index].repaired_this_turn
                            && self.buildings[index].hp < self.buildings[index].max_hp
                        {
                            let _ = self.spend_resources(player, cost);
                            let b = &mut self.buildings[index];
                            b.repaired_this_turn = true;
                            b.hp = (b.hp + b.max_hp * REPAIR_HP_NUM / REPAIR_HP_DEN).min(b.max_hp);
                        }
                    }
                }
            }
            Command::EndTurn { .. } => {
                self.end_turn();
            }
        }
    }

    /// The resource cost of repairing `building` this turn (the building's
    /// blueprint price scaled by the repair fraction); `None` when it cannot
    /// be repaired.
    pub fn repair_cost(&self, building: EntityId) -> Option<ResourceBundle> {
        let b = self.any_building(building)?;
        if !b.is_alive() || b.hp >= b.max_hp {
            return None;
        }
        let mut cost = building_stats(b.btype)
            .resource_cost
            .scaled_floor(REPAIR_COST_NUM, REPAIR_COST_DEN);
        if cost.total_value() < REPAIR_MIN_COST {
            cost.ore = REPAIR_MIN_COST;
        }
        Some(cost)
    }

    // -- movement ------------------------------------------------------------

    /// Set or replace a durable destination, then consume as much of the
    /// current activation's MP as possible. The target is retained in the
    /// unit so later own turns can continue the same march automatically.
    fn execute_move_group(&mut self, player: Player, units: &[EntityId], waypoint: (u8, u8)) {
        let blocked = self.blocked_grid();
        // The ordered waypoint is often a building (e.g. the enemy HQ):
        // retarget to the nearest free tile beside it so ground units march
        // next to structures rather than onto them. Aircraft may still use
        // the original tile as their destination.
        let target = if blocked[crate::map::tile_index(waypoint.0, waypoint.1)] {
            self.nearest_free_tile(waypoint).unwrap_or(waypoint)
        } else {
            waypoint
        };
        for &id in units {
            if let Some(u) = self.unit_mut(player, id) {
                if u.is_alive() {
                    u.move_target = Some(target);
                }
            }
        }
        self.resolve_move_orders_for(player, units);
    }

    fn execute_clear_move(&mut self, player: Player, units: &[EntityId]) {
        for &id in units {
            if let Some(u) = self.unit_mut(player, id) {
                u.move_target = None;
            }
        }
    }

    /// Resolve a subset of movement orders in the supplied order. Callers that
    /// need fully deterministic whole-army behavior pass ascending entity ids.
    fn resolve_move_orders_for(&mut self, player: Player, requested: &[EntityId]) {
        let mut ids: Vec<EntityId> = requested
            .iter()
            .copied()
            .filter(|id| self.unit(player, *id).is_some())
            .collect();
        ids.sort_unstable();
        ids.dedup();
        for id in ids {
            self.resolve_unit_move(id);
        }
    }

    /// Resolve every durable order for `player` at the start of that player's
    /// activation. Units are processed by creation id, so group movement and
    /// temporary unit blockers resolve identically on native and WASM.
    fn resolve_all_move_orders(&mut self, player: Player) {
        let ids: Vec<EntityId> = self
            .units
            .iter()
            .filter(|u| u.owner == player && u.is_alive() && u.move_target.is_some())
            .map(|u| u.id)
            .collect();
        self.resolve_move_orders_for(player, &ids);
    }

    fn resolve_unit_move(&mut self, id: EntityId) {
        let Some((mut target, mp, fly, from)) = self
            .units
            .iter()
            .find(|u| u.id == id)
            .map(|u| (u.move_target, u.mp, unit_stats(u.utype).air, u.tile))
        else {
            return;
        };
        let Some(mut target_tile) = target.take() else {
            return;
        };
        if mp <= 0 {
            return;
        }

        let blocked = self.blocked_grid();
        if !fly && blocked[crate::map::tile_index(target_tile.0, target_tile.1)] {
            target_tile = self.nearest_free_tile(target_tile).unwrap_or(target_tile);
            if let Some(u) = self.units.iter_mut().find(|u| u.id == id) {
                u.move_target = Some(target_tile);
            }
        }
        let Some(path) = self.map.find_path(from, target_tile, &blocked, fly) else {
            return;
        };

        // Walk as far as MP allows, paying each destination tile's terrain
        // cost and stopping before any tile occupied by another unit. A unit
        // blocker is temporary: the durable target remains for the next turn.
        let mut spent = 0i32;
        let mut dest = from;
        for &next in &path {
            let cost = self.map.move_cost(dest, next, fly);
            if spent + cost > mp {
                break;
            }
            if self.unit_at(next).is_some_and(|occupant| occupant != id) {
                break;
            }
            spent += cost;
            dest = next;
        }
        if let Some(u) = self.units.iter_mut().find(|u| u.id == id) {
            if spent > 0 {
                u.tile = dest;
                u.mp -= spent;
                u.moved = true;
            }
            if dest == target_tile {
                u.move_target = None;
            }
        }
    }

    /// The tile a unit with a pending move order will occupy once its move
    /// resolves this activation — walk toward `move_target` as far as current
    /// MP allows, stopping before blocked/occupied tiles (identical walk logic
    /// to `resolve_unit_move`, read-only). Used so a move-then-fire attack
    /// originates from where the unit will be at end of activation, not from
    /// its pre-move origin — otherwise right-clicking a just-marched unit's
    /// target always reports "out of range". Pure (no mutation), so it is
    /// safe to call from validation and stays deterministic.
    pub(crate) fn attack_origin(&self, u: &crate::entity::Unit) -> (u8, u8) {
        let Some(target) = u.move_target else {
            return u.tile;
        };
        if u.mp <= 0 {
            return u.tile;
        }
        let from = u.tile;
        let fly = unit_stats(u.utype).air;
        let blocked = self.blocked_grid();
        let mut target_tile = target;
        if !fly && blocked[crate::map::tile_index(target_tile.0, target_tile.1)] {
            target_tile = self.nearest_free_tile(target_tile).unwrap_or(target_tile);
        }
        let Some(path) = self.map.find_path(from, target_tile, &blocked, fly) else {
            return u.tile;
        };
        let mut spent = 0i32;
        let mut dest = from;
        for &next in &path {
            let cost = self.map.move_cost(dest, next, fly);
            if spent + cost > u.mp {
                break;
            }
            if self.unit_at(next).is_some_and(|occupant| occupant != u.id) {
                break;
            }
            spent += cost;
            dest = next;
        }
        if spent > 0 {
            dest
        } else {
            u.tile
        }
    }

    /// Preview the deterministic route for a unit's current durable order.
    /// This is presentation data only; execution still happens through the
    /// same server-side resolver.
    pub fn movement_path(&self, id: EntityId) -> Option<Vec<(u8, u8)>> {
        let u = self.any_unit(id)?;
        let target = u.move_target?;
        let blocked = self.blocked_grid();
        let target =
            if !unit_stats(u.utype).air && blocked[crate::map::tile_index(target.0, target.1)] {
                self.nearest_free_tile(target)?
            } else {
                target
            };
        self.map
            .find_path(u.tile, target, &blocked, unit_stats(u.utype).air)
    }

    // -- combat ----------------------------------------------------------------

    /// The player's aggregate research modifiers (integers: /100 numerators).
    pub fn tech_effects(&self, player: Player) -> TechEffects {
        let r = &self.research[player.index()];
        let mut e = TechEffects::base();
        for t in &r.researched {
            use TechId::*;
            match t {
                HighExplosive => e.dmg_num += 25,
                CompositeArmor => e.hp_num += 25,
                TargetingOptics => e.range_add += 1,
                EfficientRefining => e.yield_num += 25,
                TitaniumAlloys => e.hp_num += 25,
                AerialSuperiority => {
                    e.air_dmg_num += 25;
                    e.air_range_add += 1;
                }
                Superconductors => e.power_num += 50,
                CrystalNanotech => {
                    e.hp_num += 25;
                    e.dmg_num += 25;
                }
                RocketPropulsion | AdvancedBallistics => {}
            }
        }
        // Advanced Ballistics adds +1 range on top of Optics.
        if r.has(TechId::AdvancedBallistics) {
            e.range_add += 1;
        }
        e
    }

    /// Effective attack damage of a unit after research. (The anti-air rule
    /// and terrain defense are applied separately at the attack site.)
    pub(crate) fn effective_damage(&self, utype: UnitType, owner: Player, hp: i32) -> i32 {
        let stats = unit_stats(utype);
        let e = self.tech_effects(owner);
        let base = stats.damage * e.dmg_num / 100;
        let dmg = if stats.air {
            base * e.air_dmg_num / 100
        } else {
            base
        };
        // Advance-Wars scaling: damaged units deal proportionally less.
        dmg * hp / stats.hp.max(1)
    }

    /// Effective max HP of a newly trained unit after research.
    pub(crate) fn effective_max_hp(&self, utype: UnitType, owner: Player) -> i32 {
        let stats = unit_stats(utype);
        stats.hp * self.tech_effects(owner).hp_num / 100
    }

    /// Effective range of a unit after research.
    pub(crate) fn effective_range(&self, utype: UnitType, owner: Player) -> i32 {
        let stats = unit_stats(utype);
        let e = self.tech_effects(owner);
        stats.range_tiles + e.range_add + if stats.air { e.air_range_add } else { 0 }
    }

    fn execute_attack(&mut self, player: Player, units: &[EntityId], target: EntityId) {
        // Snapshot the target's position once; it cannot move mid-resolution.
        let enemy = player.enemy();
        let target_tile = self
            .units
            .iter()
            .find(|u| u.id == target && u.owner == enemy && u.is_alive())
            .map(|u| u.tile)
            .or_else(|| {
                self.buildings
                    .iter()
                    .find(|b| b.id == target && b.owner == enemy && b.is_alive())
                    .map(|b| b.tile)
            });
        let Some(target_tile) = target_tile else {
            return;
        };

        for &id in units {
            let Some(u) = self.unit(player, id) else {
                continue;
            };
            if !u.is_alive() || u.acted {
                continue;
            }
            let (utype, owner, hp, max_hp, tile) = (
                u.utype,
                u.owner,
                u.hp,
                u.max_hp,
                // Fire from where the unit will be after its pending move
                // resolves this activation (move-then-fire), not its origin.
                self.attack_origin(u),
            );
            let stats = unit_stats(utype);
            let range = self.effective_range(utype, owner);
            let d = crate::tiles::chebyshev(tile.0, tile.1, target_tile.0, target_tile.1);
            if d > range || d < stats.min_range_tiles {
                continue; // out of this unit's envelope; skips without spending
            }

            // Primary strike. Anti-air rule: non-AA ground units deal half
            // damage to air targets. Terrain defense: the defender's tile
            // reduces incoming damage (forest 20%, hills 30%).
            let target_is_air = self
                .any_unit(target)
                .is_some_and(|t| unit_stats(t.utype).air);
            let mut dmg = self.effective_damage(utype, owner, hp);
            if target_is_air && !stats.aa {
                dmg /= 2;
            }
            dmg = self.apply_terrain_defense(dmg, target_tile);
            self.apply_damage(target, dmg);

            // Counterattack: surviving direct-combat defenders strike back at
            // the attacker. Turrets never counter here (they auto-fire on
            // their own turn); artillery never counters (out of its min range
            // envelope unless the attacker stood inside it — handled by the
            // same range check below).
            let mut countered = false;
            let defender_is_unit = self.units.iter().any(|x| x.id == target && x.is_alive());
            if defender_is_unit {
                if let Some(d) = self.any_unit(target) {
                    let dstats = unit_stats(d.utype);
                    let drange = self.effective_range(d.utype, d.owner);
                    let dd = crate::tiles::chebyshev(d.tile.0, d.tile.1, tile.0, tile.1);
                    if dd <= drange && dd >= dstats.min_range_tiles {
                        let mut cdmg = self.effective_damage(d.utype, d.owner, d.hp);
                        // The attacker is air and the defender lacks AA: half.
                        if stats.air && !dstats.aa {
                            cdmg /= 2;
                        }
                        cdmg = self.apply_terrain_defense(cdmg, tile);
                        self.apply_damage(id, cdmg);
                        countered = true;
                    }
                }
            }

            if let Some(u) = self.unit_mut(player, id) {
                u.acted = true;
            }
            self.push_event(EventKind::Attacked {
                attacker: id,
                target,
                damage: dmg,
                countered,
            });
            let _ = max_hp;
        }
    }

    /// Apply damage to a unit or building by id. Deaths are marked (hp <= 0);
    /// actual removal happens in `sweep_dead`.
    /// Reduce `dmg` by the standing terrain's defense reduction.
    fn apply_terrain_defense(&self, dmg: i32, tile: (u8, u8)) -> i32 {
        let red = self.map.terrain_at(tile.0, tile.1).defense_reduction();
        if red > 0 {
            dmg * (100 - red) / 100
        } else {
            dmg
        }
    }

    fn apply_damage(&mut self, id: EntityId, amount: i32) {
        if let Some(u) = self.units.iter_mut().find(|u| u.id == id) {
            u.hp -= amount;
            return;
        }
        if let Some(b) = self.buildings.iter_mut().find(|b| b.id == id) {
            b.hp -= amount;
        }
    }

    /// Remove dead entities (ascending id order preserved by retain).
    pub(crate) fn sweep_dead(&mut self) {
        let dead_units: Vec<EntityId> = self
            .units
            .iter()
            .filter(|u| !u.is_alive())
            .map(|u| u.id)
            .collect();
        for id in dead_units {
            if let Some(u) = self.units.iter().find(|u| u.id == id) {
                self.push_event(EventKind::UnitDied { id, owner: u.owner });
            }
        }
        self.units.retain(|u| u.is_alive());

        let dead_buildings: Vec<EntityId> = self
            .buildings
            .iter()
            .filter(|b| !b.is_alive())
            .map(|b| b.id)
            .collect();
        for id in dead_buildings {
            if let Some(b) = self.buildings.iter().find(|b| b.id == id) {
                self.push_event(EventKind::BuildingDestroyed { id, owner: b.owner });
            }
        }
        self.buildings.retain(|b| b.is_alive());
    }

    // -- turn lifecycle ---------------------------------------------------------

    /// End the active player's turn and run the full lifecycle:
    /// turret fire → sweep → fog → win check → opponent start-of-turn
    /// (income → production → resets → fog).
    pub fn end_turn(&mut self) {
        if self.is_over() {
            return;
        }
        let finished = self.active;

        // 1. Turrets of the finishing player fire once each (ascending id),
        //    targeting the lowest-id enemy in range.
        let turret_ids: Vec<EntityId> = self
            .buildings
            .iter()
            .filter(|b| b.owner == finished && b.is_operational())
            .filter(|b| building_stats(b.btype).damage > 0)
            .map(|b| b.id)
            .collect();
        for tid in turret_ids {
            let Some(b) = self.buildings.iter().find(|b| b.id == tid) else {
                continue;
            };
            let stats = building_stats(b.btype);
            // AATurret engages aircraft only; other turrets hit anything.
            let aa_only = b.btype == BuildingType::AATurret;
            let enemy = b.owner.enemy();
            let victim = self
                .units
                .iter()
                .filter(|u| {
                    u.owner == enemy && u.is_alive() && (!aa_only || unit_stats(u.utype).air)
                })
                .find(|u| within_range(b.tile.0, b.tile.1, u.tile.0, u.tile.1, stats.range_tiles))
                .map(|u| u.id)
                .or_else(|| {
                    if aa_only {
                        None
                    } else {
                        self.buildings
                            .iter()
                            .filter(|x| {
                                x.owner == enemy && x.is_alive() && x.btype != BuildingType::Hq
                            })
                            .find(|x| {
                                within_range(
                                    b.tile.0,
                                    b.tile.1,
                                    x.tile.0,
                                    x.tile.1,
                                    stats.range_tiles,
                                )
                            })
                            .map(|x| x.id)
                    }
                })
                // The HQ itself is a valid target when nothing else stands in
                // range — sieges must be able to finish the game.
                .or_else(|| {
                    if aa_only {
                        None
                    } else {
                        self.buildings
                            .iter()
                            .filter(|x| {
                                x.owner == enemy && x.is_alive() && x.btype == BuildingType::Hq
                            })
                            .find(|x| {
                                within_range(
                                    b.tile.0,
                                    b.tile.1,
                                    x.tile.0,
                                    x.tile.1,
                                    stats.range_tiles,
                                )
                            })
                            .map(|x| x.id)
                    }
                });
            if let Some(victim) = victim {
                let victim_tile = self
                    .any_unit(victim)
                    .map(|u| u.tile)
                    .or_else(|| self.any_building(victim).map(|b| b.tile));
                let dmg = victim_tile
                    .map(|t| self.apply_terrain_defense(stats.damage, t))
                    .unwrap_or(stats.damage);
                self.apply_damage(victim, dmg);
                self.push_event(EventKind::Attacked {
                    attacker: tid,
                    target: victim,
                    damage: dmg,
                    countered: false,
                });
            }
        }
        self.sweep_dead();
        self.fog_phase();
        self.check_win();
        if self.is_over() {
            return;
        }

        // 2. Hand over to the opponent and run their start-of-turn.
        self.active = finished.enemy();
        self.turn += 1;
        if finished == Player::P1 {
            self.round += 1;
        }
        self.start_of_turn(self.active);
    }

    /// Start-of-turn resolution for `player`: income, production, resets.
    fn start_of_turn(&mut self, player: Player) {
        self.advance_construction(player);

        // HQ income is the only passive income that does not need a claimed
        // deposit. Every operational refinery then extracts the static richness-scaled
        // yield from the resource tile underneath it. Deposits never deplete.
        self.add_resources(player, ResourceBundle::new(HQ_INCOME_PER_TURN, 0, 0, 0));
        let yield_num = self.tech_effects(player).yield_num;
        let refinery_ids: Vec<EntityId> = self
            .buildings
            .iter()
            .filter(|b| b.owner == player && b.is_operational() && b.btype.is_refinery())
            .map(|b| b.id)
            .collect();
        for rid in refinery_ids {
            let Some((resource, richness)) =
                self.buildings.iter().find(|b| b.id == rid).and_then(|b| {
                    self.map.resource_at(b.tile.0, b.tile.1).map(|resource| {
                        (resource, self.map.resource_richness_at(b.tile.0, b.tile.1))
                    })
                })
            else {
                continue;
            };
            let extracted = self.refinery_yield(resource, richness) * yield_num / 100;
            if extracted <= 0 {
                continue;
            }
            let amount = match resource {
                ResourceType::Ore => ResourceBundle::new(extracted, 0, 0, 0),
                ResourceType::Steel => ResourceBundle::new(0, extracted, 0, 0),
                ResourceType::Coal => ResourceBundle::new(0, 0, extracted, 0),
                ResourceType::Crystal => ResourceBundle::new(0, 0, 0, extracted),
            };
            self.add_resources(player, amount);
            self.push_event(EventKind::ResourceMined {
                player,
                resource,
                amount: extracted,
            });
        }

        // Research: each Tech Lab generates points; a started tech completes
        // once the pool covers its research (and crystal) cost.
        let labs = self.count_buildings(player, BuildingType::TechLab) as i32;
        self.research[player.index()].points += labs * RESEARCH_PER_LAB_PER_TURN;
        if let Some(tech) = self.research[player.index()].researching {
            let info = tech_info(tech);
            if self.research[player.index()].points >= info.research_cost
                && self.crystal[player.index()] >= info.crystal_cost
            {
                self.research[player.index()].points -= info.research_cost;
                self.crystal[player.index()] -= info.crystal_cost;
                self.research[player.index()].researched.push(tech);
                self.research[player.index()].researching = None;
                self.push_event(EventKind::ResearchComplete { player, tech });
            }
        }

        // Production: queues advance one step per turn; low power halves the
        // rate (advance only on the player's own even-numbered turns),
        // preserving the 50%-speed semantic *symmetrically*. P0's start-of-
        // turn lands on odd global turns and P1's on even, so a global
        // `turn % 2` check would freeze one side entirely under low power.
        let low_power = self.has_low_power(player);
        let own_turn_count = (self.turn + player.index() as i32) / 2;
        let advances = !low_power || own_turn_count % 2 == 0;
        if advances {
            let producer_ids: Vec<EntityId> = self
                .buildings
                .iter()
                .filter(|b| b.owner == player && b.is_operational() && !b.queue.is_empty())
                .map(|b| b.id)
                .collect();
            for bid in producer_ids {
                let Some(item) = self
                    .building(player, bid)
                    .and_then(|b| b.queue.first().copied())
                else {
                    continue;
                };
                let build_time = unit_stats(item).build_time_turns;
                let (tile, _progress, done) = {
                    let Some(b) = self.building_mut(player, bid) else {
                        continue;
                    };
                    b.progress += 1;
                    if b.progress < build_time {
                        (b.tile, b.progress, false)
                    } else {
                        (b.tile, b.progress, true)
                    }
                };
                if !done {
                    continue;
                }
                // Spawn on a free adjacent tile.
                let Some(spawn_tile) = self.pick_spawn_tile(tile) else {
                    // Nowhere to place: hold at completion (retry next turn).
                    if let Some(b) = self.building_mut(player, bid) {
                        b.progress = build_time;
                    }
                    continue;
                };
                if let Some(b) = self.building_mut(player, bid) {
                    b.progress = 0;
                    b.queue.remove(0);
                }
                let rally = self.building(player, bid).and_then(|b| b.rally);
                self.spawn_unit(player, item, spawn_tile, rally);
            }
        }

        // Reset repair flags.
        for b in self.buildings.iter_mut() {
            if b.owner == player {
                b.repaired_this_turn = false;
            }
        }

        // Reset the acting player's budget and units.
        self.budgets[player.index()].reset();
        for u in self.units.iter_mut() {
            if u.owner == player {
                u.mp = unit_stats(u.utype).mp;
                u.moved = false;
                u.acted = false;
            }
        }
        // Durable routes resolve automatically as part of the unit's own
        // turn, after fresh MP has been granted and newly-produced units have
        // been spawned.
        self.resolve_all_move_orders(player);

        self.fog_phase();
    }

    /// Advance construction sites owned by `player` by one turn. Sites reserve
    /// their tile immediately but do not provide any capability until this
    /// progress reaches the blueprint duration.
    fn advance_construction(&mut self, player: Player) {
        for building in self
            .buildings
            .iter_mut()
            .filter(|b| b.owner == player && b.is_alive())
        {
            let duration = building.construction_time();
            if building.construction_progress < duration {
                building.construction_progress = (building.construction_progress + 1).min(duration);
            }
        }
    }

    /// A free passable tile adjacent to `tile` for spawning a produced unit.
    /// Deterministic: ascending tile-index order.
    pub(crate) fn pick_spawn_tile(&self, tile: (u8, u8)) -> Option<(u8, u8)> {
        let mut candidates: Vec<(u8, u8)> = NEIGHBOR_OFFSETS
            .iter()
            .filter_map(|&(dx, dy)| {
                let (x, y) = (tile.0 as i32 + dx, tile.1 as i32 + dy);
                if x >= 0
                    && y >= 0
                    && (x as usize) < crate::map::MAP_SIZE
                    && (y as usize) < crate::map::MAP_SIZE
                {
                    Some((x as u8, y as u8))
                } else {
                    None
                }
            })
            .collect();
        candidates.sort_by_key(|t| crate::map::tile_index(t.0, t.1));
        candidates.into_iter().find(|&t| {
            self.map.is_passable(t.0, t.1)
                && self.building_at(t).is_none()
                && self.unit_at(t).is_none()
        })
    }

    pub(crate) fn spawn_unit(
        &mut self,
        owner: Player,
        utype: UnitType,
        tile: (u8, u8),
        rally: Option<(u8, u8)>,
    ) {
        let stats = unit_stats(utype);
        let max_hp = self.effective_max_hp(utype, owner);
        let id = self.alloc_id();
        self.record_entity_creation(id, owner);
        self.units.push(Unit {
            id,
            owner,
            utype,
            tile,
            hp: max_hp,
            max_hp,
            mp: stats.mp,
            move_target: rally,
            moved: false,
            acted: false,
        });
        self.push_event(EventKind::UnitTrained {
            player: owner,
            utype,
            tile,
        });
    }

    /// The nearest passable, unblocked, unit-free tile to `t` (ties broken by
    /// ascending tile index), for marches that must stop beside a structure.
    fn nearest_free_tile(&self, t: (u8, u8)) -> Option<(u8, u8)> {
        let mut best: Option<(i32, usize, (u8, u8))> = None; // (dist, tile_idx, tile)
        for r in 0..=3i32 {
            for dy in -r..=r {
                for dx in -r..=r {
                    if dx.abs() != r && dy.abs() != r {
                        continue;
                    }
                    let (x, y) = (t.0 as i32 + dx, t.1 as i32 + dy);
                    if x < 0
                        || y < 0
                        || x >= crate::map::MAP_SIZE as i32
                        || y >= crate::map::MAP_SIZE as i32
                    {
                        continue;
                    }
                    let tt = (x as u8, y as u8);
                    if self.map.is_passable(tt.0, tt.1)
                        && self.building_at(tt).is_none()
                        && self.unit_at(tt).is_none()
                    {
                        let idx = crate::map::tile_index(tt.0, tt.1);
                        if best.is_none_or(|(bd, bi, _)| r < bd || (r == bd && idx < bi)) {
                            best = Some((r, idx, tt));
                        }
                    }
                }
            }
        }
        best.map(|(_, _, tt)| tt)
    }

    // -- win condition -----------------------------------------------------------

    /// True once the match has ended (timeout or HQ destruction).
    pub fn is_over(&self) -> bool {
        // `winner` keeps snapshots produced before the explicit draw marker
        // replayable: those snapshots ended only when a winner was present.
        self.over || self.winner.is_some()
    }

    /// Remaining **military** value for timeout scoring: the cost of every
    /// living unit and building. Banked ore is deliberately excluded — it
    /// cannot win the game, and counting it rewards hoarding (a turtle that
    /// never fights beats an army-builder at timeout). The stronger fielded
    /// force is the decisive side.
    /// Number of technologies researched by `player`.
    pub fn tech_count(&self, player: Player) -> usize {
        self.research[player.index()].researched.len()
    }

    /// Fraction of passable tiles currently visible to `player` (0..=100).
    /// Used for the map-control victory condition.
    pub fn map_control_percent(&self, player: Player) -> i32 {
        let view = self.fog_view(player);
        // Count only passable explored tiles so an impassable lake/mountain in
        // view can't inflate the numerator past 100% (pure scouting shouldn't
        // be able to win map control).
        let explored = view
            .explored
            .iter()
            .zip(&self.map.passable)
            .filter(|&(&e, &p)| e && p)
            .count();
        let passable = self.map.passable.iter().filter(|&&p| p).count().max(1);
        ((explored * 100 / passable).min(100)) as i32
    }

    /// Integrity check for deserialized state: every reachable grid struct
    /// must be well-formed before any fog/pathfinding accessor indexes into
    /// the tile arrays. Returns `false` (rather than panicking) so a corrupt
    /// or crafted save is rejected at the load boundary instead of crashing a
    /// handler task further down the line.
    pub fn validate(&self) -> bool {
        let m = &self.map;
        let len_ok = m.passable.len() == MAP_TILES
            && m.terrain.len() == MAP_TILES
            && m.elevation.len() == MAP_TILES
            && m.moisture.len() == MAP_TILES
            && m.temperature.len() == MAP_TILES
            && m.resource_kind.len() == MAP_TILES
            && m.richness.len() == MAP_TILES
            && m.ore.len() == MAP_TILES
            && m.steel.len() == MAP_TILES
            && m.coal.len() == MAP_TILES
            && m.crystal.len() == MAP_TILES;
        if !len_ok {
            return false;
        }
        let tile_ok = |t: (u8, u8)| t.0 < MAP_SIZE as u8 && t.1 < MAP_SIZE as u8;
        self.buildings.iter().all(|b| tile_ok(b.tile))
            && self.units.iter().all(|u| tile_ok(u.tile))
            && self.map.hq_tiles.iter().all(|&t| tile_ok(t))
    }

    pub fn remaining_value(&self, player: Player) -> i32 {
        let mut value = 0;
        for u in &self.units {
            if u.owner == player {
                value += unit_stats(u.utype).cost;
            }
        }
        for b in &self.buildings {
            if b.owner == player {
                value += building_stats(b.btype).cost;
            }
        }
        value
    }

    /// Check and record the win condition. Call after every combat resolution
    /// and at end of turn.
    pub fn check_win(&mut self) {
        if self.is_over() {
            return;
        }
        // HQ destroyed?
        let p0_dead = self.hq(Player::P0).is_none();
        let p1_dead = self.hq(Player::P1).is_none();
        if p0_dead && p1_dead {
            self.winner = None;
            self.win_reason = Some(WinReason::HqDestroyed);
            self.over = true;
            return;
        }
        if p0_dead {
            self.winner = Some(Player::P1);
            self.win_reason = Some(WinReason::HqDestroyed);
            self.over = true;
            return;
        }
        if p1_dead {
            self.winner = Some(Player::P0);
            self.win_reason = Some(WinReason::HqDestroyed);
            self.over = true;
            return;
        }
        // Alternative victory: science (all 10 techs researched).
        if self.tech_count(Player::P0) >= 10 {
            self.winner = Some(Player::P0);
            self.win_reason = Some(WinReason::ScienceVictory);
            self.over = true;
            return;
        }
        if self.tech_count(Player::P1) >= 10 {
            self.winner = Some(Player::P1);
            self.win_reason = Some(WinReason::ScienceVictory);
            self.over = true;
            return;
        }
        // Alternative victory: map control (≥ 60% of passable tiles explored).
        if self.map_control_percent(Player::P0) >= 60 {
            self.winner = Some(Player::P0);
            self.win_reason = Some(WinReason::MapControl);
            self.over = true;
            return;
        }
        if self.map_control_percent(Player::P1) >= 60 {
            self.winner = Some(Player::P1);
            self.win_reason = Some(WinReason::MapControl);
            self.over = true;
            return;
        }
        // Timeout? (`timeout_turns <= 0` means no limit.)
        if self.config.timeout_turns > 0 && self.turn > self.config.timeout_turns {
            let v0 = self.remaining_value(Player::P0);
            let v1 = self.remaining_value(Player::P1);
            self.win_reason = Some(WinReason::Timeout);
            self.winner = match v0.cmp(&v1) {
                std::cmp::Ordering::Greater => Some(Player::P0),
                std::cmp::Ordering::Less => Some(Player::P1),
                std::cmp::Ordering::Equal => None,
            };
            self.over = true;
        }
    }
}
