//! The research tech tree: technologies players unlock by spending research
//! points (generated by Tech Labs) and, for the top tier, crystal.
//!
//! Research is deterministic and integer-only: points accrue into a pool each
//! own turn; `StartResearch` pins the currently-researched tech; the tech
//! completes (cost deducted) as soon as the pool covers it and the crystal
//! requirement is met. Effects are computed as integer multipliers/addends by
//! `crate::game::Game` from the player's `researched` set.

use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize, Debug)]
pub enum TechId {
    /// +25% unit damage (all units).
    HighExplosive,
    /// +25% unit HP (all units).
    CompositeArmor,
    /// +1 attack range (all units).
    TargetingOptics,
    /// +25% refinery & crystal-refinery yield.
    EfficientRefining,
    /// Unlocks the Rocket Trooper and SAM launcher.
    RocketPropulsion,
    /// +25% unit HP (stacks with Composite Armor).
    TitaniumAlloys,
    /// +25% air damage and +1 air range.
    AerialSuperiority,
    /// +50% power output from power plants.
    Superconductors,
    /// +25% HP *and* damage for all units (top tier, costs crystal).
    CrystalNanotech,
    /// +1 attack range for all units (stacks with Targeting Optics).
    AdvancedBallistics,
}

pub const ALL_TECHS: [TechId; 10] = [
    TechId::HighExplosive,
    TechId::CompositeArmor,
    TechId::TargetingOptics,
    TechId::EfficientRefining,
    TechId::RocketPropulsion,
    TechId::TitaniumAlloys,
    TechId::AerialSuperiority,
    TechId::Superconductors,
    TechId::CrystalNanotech,
    TechId::AdvancedBallistics,
];

pub struct TechInfo {
    pub id: TechId,
    pub name: &'static str,
    pub description: &'static str,
    /// Research points needed to complete the tech.
    pub research_cost: i32,
    /// Crystal needed (deducted at completion; 0 = none).
    pub crystal_cost: i32,
    pub prereqs: &'static [TechId],
}

pub fn tech_info(id: TechId) -> TechInfo {
    use TechId::*;
    match id {
        HighExplosive => TechInfo {
            id,
            name: "High-Explosive Payloads",
            description: "Army-wide +25% attack damage.",
            research_cost: 150,
            crystal_cost: 0,
            prereqs: &[],
        },
        CompositeArmor => TechInfo {
            id,
            name: "Composite Armor",
            description: "Army-wide +25% hit points.",
            research_cost: 150,
            crystal_cost: 0,
            prereqs: &[],
        },
        TargetingOptics => TechInfo {
            id,
            name: "Targeting Optics",
            description: "All units gain +1 attack range.",
            research_cost: 200,
            crystal_cost: 0,
            prereqs: &[],
        },
        EfficientRefining => TechInfo {
            id,
            name: "Efficient Refining",
            description: "Refineries and crystal refineries yield +25%.",
            research_cost: 120,
            crystal_cost: 0,
            prereqs: &[],
        },
        RocketPropulsion => TechInfo {
            id,
            name: "Rocket Propulsion",
            description: "Unlocks the Rocket Trooper and SAM launcher.",
            research_cost: 350,
            crystal_cost: 0,
            prereqs: &[HighExplosive],
        },
        TitaniumAlloys => TechInfo {
            id,
            name: "Titanium Alloys",
            description: "Army-wide +25% hit points (stacks with Composite Armor).",
            research_cost: 400,
            crystal_cost: 0,
            prereqs: &[CompositeArmor],
        },
        AerialSuperiority => TechInfo {
            id,
            name: "Aerial Superiority",
            description: "Air units deal +25% damage and gain +1 range.",
            research_cost: 350,
            crystal_cost: 0,
            prereqs: &[HighExplosive],
        },
        Superconductors => TechInfo {
            id,
            name: "Superconductors",
            description: "Power plants generate +50% power.",
            research_cost: 300,
            crystal_cost: 0,
            prereqs: &[EfficientRefining],
        },
        CrystalNanotech => TechInfo {
            id,
            name: "Crystal Nanotech",
            description: "Army-wide +25% hit points and damage. Requires crystal.",
            research_cost: 600,
            crystal_cost: 20,
            prereqs: &[TitaniumAlloys],
        },
        AdvancedBallistics => TechInfo {
            id,
            name: "Advanced Ballistics",
            description: "All units gain +1 attack range (stacks with Optics).",
            research_cost: 600,
            crystal_cost: 0,
            prereqs: &[TargetingOptics],
        },
    }
}

pub fn prereqs_met(id: TechId, researched: &[TechId]) -> bool {
    tech_info(id).prereqs.iter().all(|p| researched.contains(p))
}
