//! Fitness evaluation: shaped match fitness and the bootstrap economy metric.
//! Pure — runs headless matches and returns numbers; the server supplies
//! scheduling/parallelism.

use crucible_ai::{run_match_detailed, Bot, DetailedOutcome, GenomeBot};
use crucible_sim::{
    building_stats, unit_stats, BuildingType, Command, Game, GameConfig, Map, Player,
};

/// A bot that does nothing (used as a passive opponent for bootstrap stages).
pub struct Noop;

impl Bot for Noop {
    fn name(&self) -> &'static str {
        "noop"
    }
    fn decide(&mut self, _game: &Game, player: Player) -> Vec<Command> {
        // A passive opponent: it issues nothing but still ends its turn, so
        // alternating-turn matches against it always progress.
        vec![Command::EndTurn { player }]
    }
}

/// Shaped match fitness from a player's perspective (see plan §5.4):
/// win +1 / draw +0.1 / loss −1, + 0.25 × value margin, − 0.2 anti-rush
/// damping for matches decided inside the 12-turn rush window.
pub fn shaped_fitness(d: &DetailedOutcome, player: Player) -> f32 {
    let o = d.outcome;
    let base = if o.won_by(player) {
        1.0
    } else if o.winner.is_none() {
        0.1
    } else {
        -1.0
    };

    let (own, enemy) = if player == Player::P0 {
        (d.p0_value, d.p1_value)
    } else {
        (d.p1_value, d.p0_value)
    };
    let total = (own + enemy) as f32;
    let margin = if total > 0.0 {
        (own - enemy) as f32 / total
    } else {
        0.0
    };
    let anti_rush = if o.duration_turns < 12 { -0.2 } else { 0.0 };
    base + 0.25 * margin + anti_rush
}

/// Mean shaped fitness of `genome` against a fresh opponent each match, with
/// both spawn sides played (mirror fairness).
pub fn evaluate_vs(
    genome: &[f32],
    seeds: &[u64],
    config: &GameConfig,
    mut make_opponent: impl FnMut() -> Box<dyn Bot>,
) -> f32 {
    let mut total = 0.0f32;
    let n = (seeds.len() * 2) as f32;
    for &seed in seeds {
        let mut g0 = GenomeBot::new(genome.to_vec());
        let mut opp0 = make_opponent();
        let d0 = run_match_detailed(seed, config, &mut g0, opp0.as_mut());
        total += shaped_fitness(&d0, Player::P0);

        let mut g1 = GenomeBot::new(genome.to_vec());
        let mut opp1 = make_opponent();
        let d1 = run_match_detailed(seed, config, opp1.as_mut(), &mut g1);
        total += shaped_fitness(&d1, Player::P1);
    }
    total / n
}

/// Bootstrap stage 1 fitness: total resource yield generated by `genome`
/// alone within `turns` game turns, averaged over seeds. Deposits are infinite,
/// so the signal measures claimed refinery output rather than map depletion.
///
/// The solo shaping loop drives time explicitly: the bot is polled on its own
/// turn, then the turn is ended (whoever holds it) so the schedule cannot
/// stall on a genome that never issues [`Command::EndTurn`] itself.
pub fn evaluate_economy(genome: &[f32], seeds: &[u64], config: &GameConfig, turns: i32) -> f32 {
    let mut total = 0.0f32;
    for &seed in seeds {
        let mut g = Game::new(Map::generate(seed), config.clone());
        let mut bot = GenomeBot::new(genome.to_vec());
        while g.turn < turns && !g.is_over() {
            if g.active == Player::P0 {
                let cmds = bot.decide(&g, Player::P0);
                let _ = g.apply_commands(Player::P0, &cmds);
            }
            g.end_turn();
        }
        let generated: i32 = g
            .events
            .iter()
            .filter_map(|event| match &event.kind {
                crucible_sim::EventKind::ResourceMined { player, amount, .. }
                    if *player == Player::P0 =>
                {
                    Some(*amount)
                }
                // Read old event records too, so legacy snapshots remain a
                // valid training input while all new games use ResourceMined.
                crucible_sim::EventKind::OreMined { player, amount } if *player == Player::P0 => {
                    Some(*amount)
                }
                crucible_sim::EventKind::CrystalMined { player, amount }
                    if *player == Player::P0 =>
                {
                    Some(*amount)
                }
                _ => None,
            })
            .sum();
        total += generated as f32;
    }
    total / seeds.len() as f32
}

/// Combat-military value a player has on the field (combat units + military
/// buildings), used as the stage-2 production shaping signal. Refineries and
/// the HQ are economy, not army.
pub fn army_value(g: &Game, p: Player) -> i32 {
    let mut v = 0;
    for u in &g.units {
        if u.owner == p && unit_stats(u.utype).damage > 0 {
            v += unit_stats(u.utype).cost;
        }
    }
    for b in &g.buildings {
        if b.owner == p
            && matches!(
                b.btype,
                BuildingType::PowerPlant
                    | BuildingType::Barracks
                    | BuildingType::Factory
                    | BuildingType::TechLab
                    | BuildingType::Airfield
                    | BuildingType::Turret
            )
        {
            v += building_stats(b.btype).cost;
        }
    }
    v
}

/// Bootstrap stage 2 fitness: army value built by `genome` alone within
/// `turns` game turns, averaged over seeds. Higher is better. Drives time
/// exactly like [`evaluate_economy`].
pub fn evaluate_production(genome: &[f32], seeds: &[u64], config: &GameConfig, turns: i32) -> f32 {
    let mut total = 0.0f32;
    for &seed in seeds {
        let mut g = Game::new(Map::generate(seed), config.clone());
        let mut bot = GenomeBot::new(genome.to_vec());
        while g.turn < turns && !g.is_over() {
            if g.active == Player::P0 {
                let cmds = bot.decide(&g, Player::P0);
                let _ = g.apply_commands(Player::P0, &cmds);
            }
            g.end_turn();
        }
        total += army_value(&g, Player::P0) as f32;
    }
    total / seeds.len() as f32
}

/// Map a match outcome to a league result from `player`'s perspective.
pub fn outcome_for(d: &DetailedOutcome, player: Player) -> crate::league::Outcome {
    if d.outcome.won_by(player) {
        crate::league::Outcome::Win
    } else if d.outcome.winner.is_none() {
        crate::league::Outcome::Draw
    } else {
        crate::league::Outcome::Loss
    }
}

/// Mean shaped fitness of `genome` against a set of sampled opponents from
/// the population, each played on every seed, both spawn sides. Used by the
/// self-play trainer. (The reigning champion is evaluated separately via
/// [`head_to_head`] so its per-match outcomes can feed the Elo league too.)
pub fn self_play_fitness(
    genome: &[f32],
    opponents: &[Vec<f32>],
    seeds: &[u64],
    config: &GameConfig,
) -> f32 {
    let mut total = 0.0f32;
    let mut n = 0u32;
    for opp in opponents {
        total += evaluate_vs(genome, seeds, config, || -> Box<dyn Bot> {
            Box::new(GenomeBot::new(opp.clone()))
        });
        n += 1;
    }
    total / n.max(1) as f32
}

/// Play `genome` against `opponent` (a genome) on both spawn sides over
/// `seeds`. Returns the mean shaped fitness plus every individual match
/// outcome from `genome`'s perspective (for the Elo league).
pub fn head_to_head(
    genome: &[f32],
    opponent: &[f32],
    seeds: &[u64],
    config: &GameConfig,
) -> (f32, Vec<crate::league::Outcome>) {
    let mut total = 0.0f32;
    let mut outcomes = Vec::with_capacity(seeds.len() * 2);
    for &seed in seeds {
        let mut g0 = GenomeBot::new(genome.to_vec());
        let mut o0 = Box::new(GenomeBot::new(opponent.to_vec()));
        let d0 = run_match_detailed(seed, config, &mut g0, o0.as_mut());
        total += shaped_fitness(&d0, Player::P0);
        outcomes.push(outcome_for(&d0, Player::P0));

        let mut g1 = GenomeBot::new(genome.to_vec());
        let mut o1 = Box::new(GenomeBot::new(opponent.to_vec()));
        let d1 = run_match_detailed(seed, config, o1.as_mut(), &mut g1);
        total += shaped_fitness(&d1, Player::P1);
        outcomes.push(outcome_for(&d1, Player::P1));
    }
    (total / (seeds.len().max(1) * 2) as f32, outcomes)
}

/// Total ore a player has spent (units + buildings), for income accounting.
pub fn spent_value(g: &Game, p: Player) -> i32 {
    let mut v = 0;
    for u in &g.units {
        if u.owner == p {
            v += unit_stats(u.utype).cost;
        }
    }
    for b in &g.buildings {
        if b.owner == p && b.btype != BuildingType::Hq {
            v += building_stats(b.btype).cost;
        }
    }
    v
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn shaped_fitness_rewards_wins() {
        let mut g0 = GenomeBot::new(vec![0.0; crucible_ai::GENOME_LEN]);
        let mut noop = Noop;
        let cfg = GameConfig::default();
        let d = run_match_detailed(1, &cfg, &mut g0, &mut noop);
        // A genome of all zeros never acts, so the match should time out with
        // both HQs intact; winner is the higher-value side (a draw-ish result).
        let f = shaped_fitness(&d, Player::P0);
        assert!(f.is_finite());
    }

    #[test]
    fn economy_fitness_is_deterministic_and_nonnegative() {
        let genome = crucible_ai::init(&mut crucible_sim::Rng::from_seed(9));
        let cfg = GameConfig {
            timeout_turns: 10_000,
            ..GameConfig::default()
        };
        let a = evaluate_economy(&genome, &[11], &cfg, 30);
        let b = evaluate_economy(&genome, &[11], &cfg, 30);
        assert_eq!(a, b);
        assert!(a >= 0.0);
    }
}
